### PR TITLE
Fixing bug with HTML string loaders. Resolves #47.

### LINKED ISSUE #47: Pure HTML Loader via HTMLLayoutData causing a loading error
When we try to configure the loader ui via the `contructRoutes` using a pure HTML loader it throws the following error

```
10:03:44.584 Navigated to http://localhost:9000/
10:03:45.306 load.js:96 single-spa minified message #37: See https://single-spa.js.org/error/?code=37&arg=application&arg=@react-mf/navbar&arg=[null,{"__esModule":true}] (2) [null, Module]
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
X @ single-spa.min.js:2
(anonymous) @ single-spa.min.js:2
Promise.then (async)
f @ single-spa.min.js:2
Lt @ single-spa.min.js:2
Pt @ single-spa.min.js:2
./src/root-config.js @ root-config.js:29
__webpack_require__ @ bootstrap:18
0 @ react-mf-root-config.js:9977
__webpack_require__ @ bootstrap:18
(anonymous) @ bootstrap:82
execute @ bootstrap:83
i @ system.min.js:4
e @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
(anonymous) @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
w.import @ system.min.js:4
o.import @ system.min.js:4
(anonymous) @ (index):46
10:03:45.307 app-errors.js:75 single-spa minified message #30: See https://single-spa.js.org/error/?code=30&arg=LOADING_SOURCE_CODE&arg=@react-mf/navbar
l @ single-spa.min.js:2
a @ single-spa.min.js:2
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
X @ single-spa.min.js:2
(anonymous) @ single-spa.min.js:2
Promise.then (async)
f @ single-spa.min.js:2
Lt @ single-spa.min.js:2
Pt @ single-spa.min.js:2
./src/root-config.js @ root-config.js:29
__webpack_require__ @ bootstrap:18
0 @ react-mf-root-config.js:9977
__webpack_require__ @ bootstrap:18
(anonymous) @ bootstrap:82
execute @ bootstrap:83
i @ system.min.js:4
e @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
(anonymous) @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
w.import @ system.min.js:4
o.import @ system.min.js:4
(anonymous) @ (index):46
```

**Steps to reproduce**

1. Clone the repo https://github.com/tsukhu/root-config
2. Run `yarn`
3. Run `yarn start`

The code in question is in the root-config.js
```
const data = {
  loaders: {
    navLoader: `<div>Loading...</div>`,
  },
};

const routes = constructRoutes(
  document.querySelector('#single-spa-layout'),
  data
);
```
 and the index.ejs file has reference to the `navLoader`
```
  <template id="single-spa-layout">
    <single-spa-router>
      <nav class="topnav">
        <application name="@react-mf/navbar" loader="navLoader"></application>
      </nav>
  ...
```

Note: If you replace the data object with a blank loader then it works

```
const data = {
  loaders: {
    navLoader: ``,
  },
};
```

### PR DESCRIPTION
**Pull request by joeldenning**
See #47

### CODE REVIEW

File: src/constructApplications.js [hunk 1]
```diff
@@ -143,17 +143,18 @@ function placeLoader(appName, appRoute, loadingPromise) {
...
     applicationEl = applicationElement;
 
-    return Promise.all([parcel.mountPromise, loadingPromise]).then((app) =>
-      parcel.unmount().then(() => {
-        if (hidElement) {
-          applicationElement.style.removeProperty("display");
-          if (applicationElement.getAttribute("style") === "") {
-            applicationElement.removeAttribute("style");
+    return Promise.all([parcel.mountPromise, loadingPromise]).then(
+      ([mountResult, app]) =>
```
Comment (joeldenning) [inline src/constructApplications.js:147]: Promise.all resolves with an array, not a single value. That was the cause of the bug.
