### PR TITLE
More dealing with ES/CJS interop with webpack. Resolves #90

### LINKED ISSUE #90: Importing single-spa-layout into new CRA build fails
In a default fresh Create React App install

```
    "single-spa": "^5.8.0",
    "single-spa-layout": "^1.1.3",
```

I get this error immediately after importing

```
./node_modules/single-spa-layout/dist/esm/single-spa-layout.min.js
Attempted import error: 'single-spa' does not contain a default export (imported as 'e').
```

Should this work?

### PR DESCRIPTION
**Pull request by joeldenning**
See #90

### CODE REVIEW

File: src/isomorphic/constructRoutes.js [hunk 1]
```diff
@@ -16,9 +16,10 @@ import { find } from "../utils/find";
 // The weird strings here are to trick rollup into not optimizing the import to avoid the * syntax
 const defaultStr = "d" + "efault";
 const pathToActiveWhenStr = "pathTo" + "ActiveWhen";
-const pathToActiveWhen = singleSpa[defaultStr]
-  ? singleSpa[defaultStr][pathToActiveWhenStr]
-  : singleSpa[pathToActiveWhenStr];
+const pathToActiveWhen =
+  typeof singleSpa[defaultStr] !== "undefined"
```
Comment (joeldenning) [inline src/isomorphic/constructRoutes.js:20]: without the `typeof` check, certain versions of webpack won't be able to use single-spa-layout.

**Review by alanquigley-toast — APPROVED** [review]
