### PR TITLE
Fix bug with trailing slashes. Resolves #64.

### LINKED ISSUE #64: LayoutEngine: route matching with only trailing "/"
**Describe the bug or question**
When defining base path of  "/something" and route path of "/", the route will only match to "/something/" and not "/something". Since route does not allow empty strings as a route.

**Expected behavior**
route "/something" will match

**Screenshots and/or console output**
If applicable, add screenshots or console output to help explain your problem.

**Additional context**
Why is empty route string not allowed when according to documentation leading and trailing slashes are not needed?

### PR DESCRIPTION
**Pull request by joeldenning**
See #64

### CODE REVIEW

File: src/isomorphic/matchRoute.js [hunk 1]
```diff
@@ -60,17 +60,25 @@ function recurseRoutes(location, routes) {
...
-      return prefix + path;
+      result = prefix + path;
     } else {
-      return prefix + "/" + path;
+      result = prefix + "/" + path;
     }
   }
+
+  if (result.substr(-1) === "/") {
+    result = result.slice(0, result.length - 1);
```
Comment (joeldenning) [inline src/isomorphic/matchRoute.js:80]: this is what fixes the bug

File: test/constructApplications.test.js [hunk 2]
```diff
@@ -333,6 +333,35 @@ describe(`constructApplications`, () => {
...
+      ],
+    });
+
+    async function loadApp() {}
+
+    const applications = constructApplications({ routes, loadApp });
+    expect(applications.length).toBe(1);
+    const app1 = applications[0];
+    expect(
+      app1.activeWhen.some((fn) => fn(new URL("http://example.com/something")))
```
Comment (joeldenning) [inline test/constructApplications.test.js:362]: Before the code changes in matchRoutes.js, this test failed.

**Review by filoxo — APPROVED** [review]
Makes sense 🙈
