### PR TITLE
Fixing loaders again. Resolves #47.

### LINKED ISSUE #46: How to activate application on "/" path only?
There's a `single-spa-router` element:

```html
  <template id="single-spa-layout">
    <single-spa-router>
      <application name="@pikabytes/admin-top-navigation"></application>
      <route path="/">
        <application name="@pikabytes/admin-dashboard"></application>
      </route>
      <route path="/content">
        <application name="@pikabytes/admin-content"></application>
      </route>
      <application name="@pikabytes/admin-bottom-navigation"></application>
    </single-spa-router>
  </template>
```

The content app is successfully activated when the path is "/content" but the dashboard is always available.

How do I activate the dashboard app only for the "/"?

### LINKED ISSUE #47: Pure HTML Loader via HTMLLayoutData causing a loading error
When we try to configure the loader ui via the `contructRoutes` using a pure HTML loader it throws the following error

```
10:03:44.584 Navigated to http://localhost:9000/
10:03:45.306 load.js:96 single-spa minified message #37: See https://single-spa.js.org/error/?code=37&arg=application&arg=@react-mf/navbar&arg=[null,{"__esModule":true}] (2) [null, Module]
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
X @ single-spa.min.js:2
(anonymous) @ single-spa.min.js:2
Promise.then (async)
f @ single-spa.min.js:2
Lt @ single-spa.min.js:2
Pt @ single-spa.min.js:2
./src/root-config.js @ root-config.js:29
__webpack_require__ @ bootstrap:18
0 @ react-mf-root-config.js:9977
__webpack_require__ @ bootstrap:18
(anonymous) @ bootstrap:82
execute @ bootstrap:83
i @ system.min.js:4
e @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
(anonymous) @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
w.import @ system.min.js:4
o.import @ system.min.js:4
(anonymous) @ (index):46
10:03:45.307 app-errors.js:75 single-spa minified message #30: See https://single-spa.js.org/error/?code=30&arg=LOADING_SOURCE_CODE&arg=@react-mf/navbar
l @ single-spa.min.js:2
a @ single-spa.min.js:2
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
(anonymous) @ single-spa.min.js:2
Promise.then (async)
X @ single-spa.min.js:2
(anonymous) @ single-spa.min.js:2
Promise.then (async)
f @ single-spa.min.js:2
Lt @ single-spa.min.js:2
Pt @ single-spa.min.js:2
./src/root-config.js @ root-config.js:29
__webpack_require__ @ bootstrap:18
0 @ react-mf-root-config.js:9977
__webpack_require__ @ bootstrap:18
(anonymous) @ bootstrap:82
execute @ bootstrap:83
i @ system.min.js:4
e @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
(anonymous) @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
w.import @ system.min.js:4
o.import @ system.min.js:4
(anonymous) @ (index):46
```

**Steps to reproduce**

1. Clone the repo https://github.com/tsukhu/root-config
2. Run `yarn`
3. Run `yarn start`

The code in question is in the root-config.js
```
const data = {
  loaders: {
    navLoader: `<div>Loading...</div>`,
  },
};

const routes = constructRoutes(
  document.querySelector('#single-spa-layout'),
  data
);
```
 and the index.ejs file has reference to the `navLoader`
```
  <template id="single-spa-layout">
    <single-spa-router>
      <nav class="topnav">
        <application name="@react-mf/navbar" loader="navLoader"></application>
      </nav>
  ...
```

Note: If you replace the data object with a blank loader then it works

```
const data = {
  loaders: {
    navLoader: ``,
  },
};
```

### PR DESCRIPTION
**Pull request by joeldenning**
See #47

### CODE REVIEW

File: src/constructApplications.js [hunk 1]
```diff
@@ -146,37 +161,25 @@ function placeLoader(appName, appRoute, loadingPromise) {
...
-  let appendedNodes = [];
-
   return {
     bootstrap: () => Promise.resolve(),
     mount: (props) =>
       Promise.resolve().then(() => {
-        nodes.forEach((node) => {
-          appendedNodes.push(props.domElement.appendChild(node.cloneNode()));
-        });
+        props.domElement.innerHTML = str;
```
Comment (joeldenning) [inline src/constructApplications.js:178]: I was doing weird things previously to try to avoid innerHTML for security purposes. But it turns out my implementation was not only buggy but also didn't provide any security (i think). So I switched to innerHTML to fix it.

File: src/constructApplications.js [hunk 2]
```diff
@@ -119,17 +119,32 @@ function placeLoader(appName, appRoute, loadingPromise) {
...
       applicationElement = document.createElement("div");
       applicationElement.id = htmlId;
       // Wait for layout engine to place this dom element in correct location
       // before it's visible
       applicationElement.style.display = "none";
-      hidElement = true;
 
       document.body.appendChild(applicationElement);
+
+      makeElementVisible = () => {
```
Comment (joeldenning) [inline src/constructApplications.js:133]: Previously we were hiding the application element (line 129) and were only unhiding once it was the app code was downloaded. That defeats the purpose of the loader. The reason we are hiding it is we need to make sure it is positioned correctly in the dom before showing it, which only occurs during the single-spa:before-mount-routing-event. So what I've done is unhide it during that event.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-layout/releases/tag/v1.0.0-beta.4
